version: 2.4.3.{build}

branches:
  only:
    - master
    - my-build

environment:
  qt_version: 5.9
  mingw_version: 53

  matrix:
    - name: win32
      platform: amd64_x86
      compiler_setup: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
      make_tool: jom
      qt: $(qt_version)\msvc2015
      suffix: msvc2015

    - name: win32
      platform: mingw
      compiler_setup: ''
      make_tool: mingw32-make
      qt: $(qt_version)\mingw$(mingw_version)_32
      suffix: mingw

init:
  - set QTDIR=C:\Qt\%qt%\bin
  - set PATH=%QTDIR%;%PATH%
  - if %platform%==mingw set PATH=C:\Qt\Tools\mingw%mingw_version%_32\bin;C:\MinGW\bin;%PATH%
  - if not %platform%==mingw set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
  - '%compiler_setup%'

before_build:
  - call acquire_bass.cmd

build_script:
  - qmake Attorney_Online_remake.pro
  - '%make_tool% -j4'

after_build:
  - dir
  - dir release

before_deploy:
  - copy bass.dll release