version: 2.4.3

branches:
  only:
    - master
    - my-build

environment:
  qt_version: 5.9
  mingw_version: 53

  matrix:
    - name: win32
      platform: amd64_x86
      compiler_setup: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
      make_tool: nmake
      qt: $(qt_version)\msvc2015
      suffix: msvc2015

    - name: win32
      platform: mingw
      compiler_setup: ''
      make_tool: mingw32-make
      qt: $(qt_version)\mingw$(mingw_version)_32
      suffix: mingw

init:
  - set QTDIR=C:\Qt\%qt%\bin
  - set PATH=%QTDIR%;%PATH%
  - if %platform%==mingw set PATH=C:\Qt\Tools\mingw%mingw_version%_32\bin;%PATH%
  - '%compiler_setup%'

before_build:
  # Acquire BASS
  - curl --verbose -H "Referer: https://www.un4seen.com/bass.html" -H "Host: www.un4seen.com" -o bass.zip https://www.un4seen.com/files/bass24.zip
  - md bass
  - cd bass
  - 7z x -y ..\bass.zip >nul
  - copy bass.dll c\bass.lib ..
  - cd..

build_script:
  - qmake Attorney_Online_remake.pro
  - '%make_tool%'

after_build:
  - dir